import { getTableName } from './tableName.js'

/**
 * Documents exactly what was included in this export — never claims a
 * capability that isn't there, and is explicit about known limitations
 * rather than presenting the output as production-ready (section 61).
 */
export function generateReadme(schema, options) {
  const fieldList = schema.fields
    .map((f) => `- **${f.label}** (\`${f.name}\`) — ${f.type}${f.validation?.required ? ', required' : ''}`)
    .join('\n')

  const sections = [`# ${schema.name}`, '']

  if (schema.description) {
    sections.push(schema.description, '')
  }

  sections.push(
    '## Overview',
    '',
    `This project was generated by FormForge from a visual form design. It contains ${
      options.frontend ? 'a working frontend' : 'no frontend (excluded from this export)'
    }${options.backend === 'php' ? ', a PHP backend' : ''}${
      options.database === 'mysql' ? ', and a MySQL schema' : ''
    }.`,
    '',
    '## Fields',
    '',
    fieldList,
    '',
  )

  sections.push('## Features', '')
  const features = []
  if (options.frontend) features.push('- Client-side validation with accessible error messages')
  if (options.backend === 'php') features.push('- Server-side validation — never trusts the client (see Security notes)')
  if (options.backend === 'php')
    features.push('- Secure file upload handling (extension allowlist, MIME sniffing, randomized filenames)')
  if (options.database === 'mysql') features.push('- Submission storage via prepared statements (PDO)')
  if (options.jsonSchema) features.push('- A standard JSON Schema representation of this form')
  sections.push(features.join('\n'), '')

  if (options.frontend) {
    sections.push(
      '## Frontend',
      '',
      '```',
      'frontend/',
      '  index.html',
      '  styles.css',
      '  script.js',
      '```',
      '',
      'Open `frontend/index.html` directly, or serve the `frontend/` directory with any static file server.',
      '',
    )
  }

  if (options.backend === 'php') {
    sections.push(
      '## Backend',
      '',
      '```',
      'backend/',
      '  api/submit.php',
      '  config/config.php',
      '  config/database.php',
      '  validation/validation.php',
      '```',
      '',
      'Requires PHP 8+. Point your web server at `backend/api/submit.php`, or run it locally with:',
      '',
      '```bash',
      'php -S localhost:8000 -t backend',
      '```',
      '',
      '### Environment variables',
      '',
      '| Variable | Purpose | Default |',
      '|---|---|---|',
      '| `DB_HOST` | MySQL host | `127.0.0.1` |',
      '| `DB_PORT` | MySQL port | `3306` |',
      '| `DB_NAME` | Database name | `formforge` |',
      '| `DB_USER` | Database user | `root` |',
      '| `DB_PASSWORD` | Database password | *(empty)* |',
      '| `UPLOAD_DIR` | Where uploaded files are stored (outside the web root) | `../../uploads` relative to `config/` |',
      '| `CORS_ALLOWED_ORIGIN` | Allowed origin for cross-origin requests | `*` |',
      '',
      'Never commit real credentials — set these in your hosting environment.',
      '',
    )
  }

  if (options.database === 'mysql') {
    sections.push(
      '## Database',
      '',
      `Run \`database/schema.sql\` against your MySQL database to create the \`${getTableName(
        schema,
      )}\` table before accepting submissions.`,
      '',
    )
  }

  sections.push(
    '## Security notes',
    '',
    '- Client-side validation (in `script.js`) is for user experience only. `submit.php` independently re-validates every field — never assume the browser already checked anything.',
    '- Password-type fields, if present in this form, are never stored anywhere in this export. A generic submissions table has no safe way to hash and manage credentials.',
    '- Uploaded files are renamed to a random filename and stored outside the web-servable root, so they can never be requested (and therefore never executed) directly by URL.',
    '- This export has not been security-audited beyond the practices above. Review it before handling sensitive data in production.',
    '',
  )

  sections.push(
    '## Customization',
    '',
    'All markup, styles, and validation rules are plain, unminified files — edit them directly. Regenerating from FormForge will overwrite these files, so keep manual changes in version control if you plan to regenerate later.',
    '',
  )

  sections.push('---', '', '_Generated by FormForge._', '')

  return sections.join('\n')
}
